#! /usr/bin/python3
# ------------------------------------------------------------------
#
#    Copyright (C) 2012 Canonical Ltd.
#
#    This program is free software; you can redistribute it and/or
#    modify it under the terms of version 2 of the GNU General Public
#    License published by the Free Software Foundation.
#
# ------------------------------------------------------------------

import pyronia.sandbox
from pyronia.common import error
import optparse
import sys

# setup exception handling
from pyronia.fail import enable_aa_exception_handler
enable_aa_exception_handler()

if __name__ == "__main__":
    argv = sys.argv
    parser = optparse.OptionParser()
    pyronia.easyprof.add_parser_policy_args(parser)
    (opt, args) = pyronia.sandbox.parse_args(sys.argv, parser)

    if len(args) < 1:
        error("Must specify binary")

    binary = args[0]
    if not pyronia.sandbox.check_requirements(binary):
        sys.exit(1)

    if opt.withx:
        rc, report = pyronia.sandbox.run_xsandbox(args, opt)
    else:
        rc, report = pyronia.sandbox.run_sandbox(args, opt)

    pyronia.common.msg(report)
    sys.exit(rc)
